server:
  port: 8099
  tomcat:
    max-connections: 100
    min-spare-threads: 10
    accept-count: 10

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

#mysql
spring:
  application:
    #服务别名（注册到Eureka的名称，集群的时候，同一个服务这个名字必须要一致）
    name: api
  datasource:
    url: jdbc:mysql://118.25.215.68:3306/volarpad_cloud?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    include: eureka

  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

mybatis:
  mapper-locations: classpath:mapper/*.xml