#Eureka配置
eureka:
  #Eureka服务器地址、端口号，多个地址用英文逗号隔开
  client:
    service-url:
      #注册地址
      defaultZone:  http://10.206.33.219:8761/eureka/,http://10.206.33.223:8761/eureka/
    #需要将自己注册给服务中心
    register-with-eureka: false
    #需要检索已经注册到Eureka注册中心的服务信息
    fetch-registry: false
  #心跳检测与续约时间配置（测试开发环境设小点，方便调试）
  instance:
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，超过则剔除改服务的注册信息，单位为秒
    lease-expiration-duration-in-seconds: 30
    #Eureka客户端向服务器端发送心跳的时间间隔
    lease-renewal-interval-in-seconds: 10
    #服务id
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 30000